name: golangci-lint

on: [push, pull_request]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'  # Replace with the version of Go you are using

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --issues-exit-code=0 --timeout=5m
